
package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import conexion.Conexiones;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author USUARIO
 */
public class login extends javax.swing.JFrame {

    
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono.png"));
        setIconImage(icono);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_logo = new javax.swing.JLabel();
        l_usuario = new javax.swing.JLabel();
        l_passwor = new javax.swing.JLabel();
        camp_usuario = new javax.swing.JTextField();
        camp_pasword = new javax.swing.JPasswordField();
        b_aceder = new javax.swing.JButton();
        b_salir = new javax.swing.JButton();
        l_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login de usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo verde.png"))); // NOI18N
        getContentPane().add(l_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 290, 170));

        l_usuario.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        l_usuario.setText("ingrese su usuario:");
        getContentPane().add(l_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 150, 30));

        l_passwor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        l_passwor.setText("ingrese contraseña");
        getContentPane().add(l_passwor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 150, 30));

        camp_usuario.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(camp_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 150, 30));
        getContentPane().add(camp_pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 150, 30));

        b_aceder.setBackground(new java.awt.Color(153, 255, 51));
        b_aceder.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        b_aceder.setText("acceder");
        b_aceder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_aceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_acederActionPerformed(evt);
            }
        });
        getContentPane().add(b_aceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 100, 50));

        b_salir.setBackground(new java.awt.Color(153, 255, 51));
        b_salir.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        b_salir.setText("salir");
        b_salir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });
        getContentPane().add(b_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 100, 50));

        l_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_login.jpg"))); // NOI18N
        l_fondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(l_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 401, 588));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int intentos=0;
    private void b_acederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_acederActionPerformed
        Connection conexion = Conexiones.conectar();
        String usuario = camp_usuario.getText();
        String clave = new String(camp_pasword.getPassword());
        PreparedStatement consulta;
        ResultSet resultado;
        int control=0;
        if (camp_usuario.getText().isEmpty()||new String(camp_pasword.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(null,"no deben haber campos vacios", "errror",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
             String sql = "SELECT * FROM usuarios WHERE nombre_usuario=? AND clave=?";
        consulta = conexion.prepareStatement(sql);
        consulta.setString(1, usuario);
        consulta.setString(2, clave);
        resultado = consulta.executeQuery();
        
             if (resultado.next()) {
               JOptionPane.showMessageDialog(null, "Login correcto", "Login", 
                       JOptionPane.INFORMATION_MESSAGE);
            // Abrir ventana principal y cerrar login
            ventanaPrincipal ventana = new ventanaPrincipal();
            ventana.setVisible(true);
            this.dispose();
            
            } else {
                 intentos ++;
              JOptionPane.showMessageDialog(null, "Usuario/contraseña incorrecta"+" Intente de nuevo.", " Error", 
                      JOptionPane.ERROR_MESSAGE);
              camp_usuario.setText("");
              camp_pasword.setText("");
            }
             if (intentos==3){
                JOptionPane.showMessageDialog(null,
                        "cantidad de intentos agotada\n"+
                                                 " su cuenta a sido bloqueada\n"+ 
                                         " contacte con soporte",
                                             "  aviso",
                        JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
        }
    }                                         

    private void B_salirActionPerformed(java.awt.event.ActionEvent evt) {                                        


    }//GEN-LAST:event_b_acederActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        // TODO add your handling code here:
        int respuesta=JOptionPane.showConfirmDialog(null, "confrima salir de la aplicacion\n",
                 "confirma salida",
                 JOptionPane.YES_NO_OPTION,
                 JOptionPane.QUESTION_MESSAGE);
         if (respuesta == JOptionPane.YES_OPTION){
             System.exit(0);
         }
    }//GEN-LAST:event_b_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_aceder;
    private javax.swing.JButton b_salir;
    private javax.swing.JPasswordField camp_pasword;
    private javax.swing.JTextField camp_usuario;
    private javax.swing.JLabel l_fondo;
    private javax.swing.JLabel l_logo;
    private javax.swing.JLabel l_passwor;
    private javax.swing.JLabel l_usuario;
    // End of variables declaration//GEN-END:variables
}
